### PR TITLE
Fix estimated fee component and transform

### LINKED ISSUE #210: Estimated Fee is not calculated on base unit
When calculated estimated fee does not return on MLAU unit: (e.g. 0.00002) but multiplied by chain decimals.
That is an inconsistency with the input that user adds (Its in base unit) so user sees 1 MLAU as input but the estimated fee appears: `Estimated source Fee: 275002585`

### PR DESCRIPTION
**Pull request by wirednkod**
Fixes #210 #171

### CODE REVIEW

File: src/components/EstimatedFee.tsx [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+  const srcChainDecimals = sourceChainDetails.apiConnection.api.registry.chainDecimals[0];
+  const { chainTokens } = targetChainDetails.apiConnection.api.registry;
+
+  const [amount, setAmount] = useState<string>('0');
+
+  useEffect(() => {
+    !estimatedFeeLoading && setAmount(transformToBaseUnit(estimatedFee || '0', srcChainDecimals));
+  }, [estimatedFee, estimatedFeeLoading, srcChainDecimals]);
+
+  return (
```
Comment (hbulgarini) [inline src/components/EstimatedFee.tsx:49]: Why are we not uncluding the loading part in this component?

```
      {estimatedFeeLoading ? (
        <Typography variant="body1" color="secondary">
          Estimated source Fee loading...
        </Typography>
      ) : (
        <EstimatedFee />
      )}
```

I see this is quite the same over the other actions.

**Review by hbulgarini — CHANGES_REQUESTED** [review]

File: src/components/EstimatedFee.tsx (hunk 1 above)
Comment (wirednkod) [reply src/components/EstimatedFee.tsx:49]: Good catch - eluded my attention as Loading is not working at the moment. Will fix

File: src/components/EstimatedFee.tsx [hunk 2]
```diff
@@ -49,9 +49,9 @@ export const EstimatedFee = (): React.ReactElement => {
   return (
     <div>
       <Typography variant="body1" color="secondary">
-        Estimated source Fee:
+        {`Estimated source Fee ${estimatedFeeLoading ? 'Loading' : ''}`}
```
Comment (tomusdrw) [inline src/components/EstimatedFee.tsx:52]:
```suggestion
        {`Estimated ${chain} Fee: ${estimatedFeeLoading ? '...' : ''}`}
```
Can we replace this to say the chain name (uppercase), have a double colon so that it's clear that it's a label for some value?

I'd also get rid of `Loading`. It's not really "loading" anything, it's being calculated and we are waiting for a response. Adding a word there is extra mental capacity imho, I'd just replace it with dots. This is totally my preference though so I'm not super strong on this.

File: src/components/EstimatedFee.tsx [hunk 3]
```diff
@@ -49,9 +49,9 @@ export const EstimatedFee = (): React.ReactElement => {
...
         <span className={`${estimatedFeeLoading ? classes.blurred : ''} ${classes.amount}`}>{amount}</span>
-        {chainTokens}
+        {!estimatedFeeLoading && chainTokens}
```
Comment (tomusdrw) [inline src/components/EstimatedFee.tsx:54]: If we switch to `...` I'd also always display tokens here (unconditionally).

File: src/util/evalUnits.ts [hunk 4]
```diff
@@ -89,3 +89,8 @@ export function evalUnits(input: string, chainDecimals: number): [BN | null, str
   }
   return [numeric, EvalMessages.SUCCESS];
 }
+
+export function transformToBaseUnit(estFee: string, chainDecimals: number): string {
+  const est = parseInt(estFee) / 10 ** chainDecimals;
+  return est.toString();
```
Comment (tomusdrw) [inline src/util/evalUnits.ts:95]: Any chance we can do it using `BN` library? Or manually? It's basically about padding with zeros and potentially adding `0.` in front. The reason I ask for this is because if `chainDecimals` are large we will again run into float issues and weird  values being displayed.

Example:
```
(235 / 10 ** 9).toString() == '2.35e-7'
```

**Review by tomusdrw — APPROVED** [review]

File: src/util/evalUnits.ts (hunk 4 above)
Comment (wirednkod) [reply src/util/evalUnits.ts:95]: Im not sure that you will ever have 235 fee... In addition is there a chance that the chain will have way more than 9 decimals?

Comment (tomusdrw) [reply src/util/evalUnits.ts:95]: It's not about our assumptions, but what Substrate is designed for. If we can make it always correct (and not only under some opinionated conditions) with a bit of more code, let's do it.

Ethereum has 18 decimals for instance and the fees are in `Gwei` so 20 Gwei should not be displayed as `(20 * 10**9/10**18).toString() === '2e-8'`

File: src/components/EstimatedFee.tsx (hunk 2 above)
Comment (hbulgarini) [reply src/components/EstimatedFee.tsx:52]: I like using three dots instead of loading ....

Regarding the chain , what it would be better is to add the corresponding chain icon instead of the chain name.

Comment (hbulgarini) [reply src/components/EstimatedFee.tsx:52]: > Regarding the chain , what it would be better is to add the corresponding chain icon instead of the chain name.

I'm not saying to do that in this PR but as a refresher we have this issue: #48

File: src/components/EstimatedFee.tsx (hunk 3 above)
Comment (hbulgarini) [reply src/components/EstimatedFee.tsx:54]: What do you mean?  not sure i get this comment.

Comment (wirednkod) [reply src/components/EstimatedFee.tsx:54]: I think Tomasz means that if we replace `Loading` with `...` There is no need to have a condition on wheather the chainTokens should appear or not (and IMO he is right)

File: src/components/EstimatedFee.tsx (hunk 2 above)
Comment (wirednkod) [reply src/components/EstimatedFee.tsx:52]: > I'm not saying to do that in this PR but as a refresher we have this issue: #48

I agree you should reopen that issue and lets do that there

**Review by hbulgarini — APPROVED** [review]
This looks good to me!

**Review by tomusdrw — CHANGES_REQUESTED** [review]
Requesting changes due to: https://github.com/paritytech/parity-bridges-ui/pull/218#discussion_r666091675

**Review by tomusdrw — APPROVED** [review]

File: src/components/EstimatedFee.tsx [hunk 5]
```diff
@@ -0,0 +1,56 @@
...
+
+  useEffect(() => {
+    !estimatedFeeLoading && setAmount(transformToBaseUnit(estimatedFee || '0', srcChainDecimals));
+  }, [estimatedFee, estimatedFeeLoading, srcChainDecimals]);
+
+  return (
+    <div>
+      <Typography variant="body1" color="secondary">
+        {`Estimated ${sourceChainDetails.chain} fee ${estimatedFeeLoading ? '...' : ''}`}
+        <span className={classes.amount}>
```
Comment (goldsteinsveta) [inline src/components/EstimatedFee.tsx:50]: Style nit: pls replace `<span>` with `<Typography variant="subtitle2" component="span">`

File: src/components/EstimatedFee.tsx [hunk 6]
```diff
@@ -0,0 +1,56 @@
...
+import { makeStyles } from '@material-ui/core/styles';
+import { Typography } from '@material-ui/core';
+import React from 'react';
+import { useEffect } from 'react';
+import { useState } from 'react';
+import { useSourceTarget } from '../contexts/SourceTargetContextProvider';
+import { useTransactionContext } from '../contexts/TransactionContext';
+import { transformToBaseUnit } from '../util/evalUnits';
+
+const useStyles = makeStyles(() => ({
```
Comment (goldsteinsveta) [inline src/components/EstimatedFee.tsx:26]: You don't need these styles really

File: src/components/EstimatedFee.tsx [hunk 7]
```diff
@@ -0,0 +1,56 @@
...
+  const [amount, setAmount] = useState<string>('0');
+
+  useEffect(() => {
+    !estimatedFeeLoading && setAmount(transformToBaseUnit(estimatedFee || '0', srcChainDecimals));
+  }, [estimatedFee, estimatedFeeLoading, srcChainDecimals]);
+
+  return (
+    <div>
+      <Typography variant="body1" color="secondary">
+        {`Estimated ${sourceChainDetails.chain} fee ${estimatedFeeLoading ? '...' : ''}`}
```
Comment (goldsteinsveta) [inline src/components/EstimatedFee.tsx:49]: I'd suggest to `${estimatedFeeLoading ? '...' : ':'}`

**Review by goldsteinsveta — APPROVED** [review]
