### PR TITLE
fix hook useBalance and replace hardcoded balances with actual balanc…

### LINKED ISSUE #49: Display balances for source and target accounts.

### PR DESCRIPTION
**Pull request by wirednkod**
…es from source and target chains; Fixes #49

### CODE REVIEW

File: src/hooks/useBalance.ts [hunk 1]
```diff
@@ -0,0 +1,89 @@
...
+// You should have received a copy of the GNU General Public License
+// along with Parity Bridges UI.  If not, see <http://www.gnu.org/licenses/>.
+import { Balance } from '@polkadot/types/interfaces';
+import { formatBalance } from '@polkadot/util';
+import BN from 'bn.js';
+import { useEffect, useState } from 'react';
+
+import { useSourceTarget } from '../contexts/SourceTargetContextProvider';
+
+type State = [string, Balance, boolean, string];
```
Comment (hbulgarini) [inline src/hooks/useBalance.ts:23]: why not creating and object instead of an array so we have a more explicit state like: 
`sourceState.balance` or `sourceState.free`

File: src/hooks/useBalance.ts [hunk 2]
```diff
@@ -0,0 +1,89 @@
...
+            }),
+            data.free,
+            data.free.isZero(),
+            data.free.registry.chainTokens[0]
+          ]);
+        })
+        .then((u): void => {
+          unsubscribeSource = u;
+        })
+        .catch(console.error);
```
Comment (hbulgarini) [inline src/hooks/useBalance.ts:60]: We use a custom logger helper : https://github.com/paritytech/parity-bridges-ui/blob/master/src/util/logger.ts to avoid `console.log` or `console.error`.

Also in case you want to show the error to the user you can dispatch the message to the snackbar component to show the error/warning/info. Here you have an example of the ussage:

https://github.com/paritytech/parity-bridges-ui/blob/master/src/hooks/useSendMessage.ts#L137

I need to confirm this , but i think that `e.message` must be provided instead of `e`

File: src/hooks/useBalance.ts [hunk 3]
```diff
@@ -0,0 +1,89 @@
...
+            }),
+            data.free,
+            data.free.isZero(),
+            data.free.registry.chainTokens[0]
+          ]);
+        })
+        .then((u): void => {
+          unsubscribeTarget = u;
+        })
+        .catch(console.error);
```
Comment (hbulgarini) [inline src/hooks/useBalance.ts:78]: same as above.

File: src/components/Account.tsx [hunk 4]
```diff
@@ -19,40 +19,47 @@ import People from '@material-ui/icons/People';
...
 
-    <div className="balances">
-      <div className="balance">
-        <p>0.1 RLTO</p>
-      </div>
-      {showDerivedBalance && (
+      <div className="balances">
         <div className="balance">
-          <p>0.1 MLAU</p>
+          <p>{source ? source[0] : '-'}</p>
```
Comment (hbulgarini) [inline src/components/Account.tsx:52]: i think that if the balance would be an object instead of an array this would be easier to read. like:
`<p>{source ? source.balance : '-'}</p>`

**Review by hbulgarini — CHANGES_REQUESTED** [review]

File: src/components/Account.tsx [hunk 5]
```diff
@@ -19,40 +19,47 @@ import People from '@material-ui/icons/People';
...
-  <Container className={className}>
-    <div className="address">
-      <div className="topAddress">
-        <People />
-        <div className="text">
-          <p>{text}</p>
+const Account = ({ className, text, value, showDerivedBalance = false }: Props) => {
+  const results = useBalance(value, true);
+  const source = results[0];
+  const target = results[1];
```
Comment (tomusdrw) [inline src/components/Account.tsx:34]:
```suggestion
  const [source, target] = useBalance(value, true);
```

File: src/hooks/useBalance.ts [hunk 6]
```diff
@@ -0,0 +1,89 @@
...
+      sourceApi.query.system
+        .account(address, ({ data }): void => {
+          setSourceState([
+            formatBalance(data.free, {
+              decimals: sourceApi.registry.chainDecimals[0],
+              forceUnit: '-',
+              withSi: providedSi
+            }),
+            data.free,
+            data.free.isZero(),
```
Comment (tomusdrw) [inline src/hooks/useBalance.ts:53]: Why is this useful? Can't you just do `source[1].isZero()` instead of `source[2]`?

File: src/hooks/useBalance.ts [hunk 7]
```diff
@@ -0,0 +1,89 @@
...
+            data.free.registry.chainTokens[0]
+          ]);
+        })
+        .then((u): void => {
+          unsubscribeSource = u;
+        })
+        .catch(console.error);
+
+      targetApi.query.system
+        .account(address, ({ data }): void => {
```
Comment (tomusdrw) [inline src/hooks/useBalance.ts:63]: This is incorrect, we shouldn't be querying the same account on both source and target - rather we need to query "bridge account" aka "derived account" on the target chain.

File: src/hooks/useBalance.ts [hunk 8]
```diff
@@ -0,0 +1,89 @@
...
+              decimals: sourceApi.registry.chainDecimals[0],
+              forceUnit: '-',
+              withSi: providedSi
+            }),
+            data.free,
+            data.free.isZero(),
+            data.free.registry.chainTokens[0]
+          ]);
+        })
+        .then((u): void => {
```
Comment (tomusdrw) [inline src/hooks/useBalance.ts:57]: Can't we use `async/await` to simplify the code?

File: src/hooks/useBalance.ts [hunk 9]
```diff
@@ -0,0 +1,89 @@
...
+    let unsubscribeSource: null | (() => void) = null;
+    let unsubscribeTarget: null | (() => void) = null;
+    if (address) {
+      sourceApi.query.system
+        .account(address, ({ data }): void => {
+          setSourceState([
+            formatBalance(data.free, {
+              decimals: sourceApi.registry.chainDecimals[0],
+              forceUnit: '-',
+              withSi: providedSi
```
Comment (tomusdrw) [inline src/hooks/useBalance.ts:50]: We need proper units and human-readable formatting here.

File: src/hooks/useBalance.ts [hunk 10]
```diff
@@ -0,0 +1,89 @@
...
+      sourceApiConnection: { api: sourceApi }
+    },
+    targetChainDetails: {
+      targetApiConnection: { api: targetApi }
+    }
+  } = useSourceTarget();
+
+  useEffect((): (() => void) => {
+    let unsubscribeSource: null | (() => void) = null;
+    let unsubscribeTarget: null | (() => void) = null;
```
Comment (tomusdrw) [inline src/hooks/useBalance.ts:42]:
```suggestion
    let unsubscribeSource = () => {};
    let unsubscribeTarget = () => {};
```
Wouldn't that work? Also if you do this, you can skip the `unsubscribeSource && ` check in the function returned from `useEffect`.

File: src/hooks/useBalance.ts (hunk 9 above)
Comment (wirednkod) [reply src/hooks/useBalance.ts:50]: I would like to discuss this a bit more in order to understand

Comment (tomusdrw) [reply src/hooks/useBalance.ts:50]: So I'm not sure exactly how `formatBalance` works and perhaps we are already doing what  I want to achieve.
I'd like the values to be displayed like that:
```
1 TOK
1 kTOK
1 MTOK
1 mTOK
```
etc. So using SI prefixes and unit symbol - i.e avoiding a situation where full number of decimals is being displayed.
My suggestion would be also to display full balance (no SI; with thousand separator) in a tooltip (`title` attribute is good enough).

Comment (tomusdrw) [reply src/hooks/useBalance.ts:50]: Discussed this offband and the API is doing exactly what I mean, the unit should be loaded from the chainspec's `properties` section and currently it's missing for Rialto & Millau, hence it displays incorrectly, but we will add it shortly.

File: src/hooks/useBalance.ts (hunk 10 above)
Comment (wirednkod) [reply src/hooks/useBalance.ts:42]: I had to follow different way due to the async/await and cause I wanted reusable functions :)

File: src/hooks/useBalance.ts (hunk 9 above)
Comment (wirednkod) [reply src/hooks/useBalance.ts:50]: > display full balance (no SI; with thousand separator) in a tooltip (title attribute is good enough).

I'll make this in different PR though (keep scope of PRs small)

**Review by hbulgarini — CHANGES_REQUESTED** [review]

File: src/hooks/useBalance.ts [hunk 11]
```diff
@@ -0,0 +1,105 @@
+// Copyright 2021 Parity Technologies (UK) Ltd.
```
[the remark this answers is not in the document]
Comment (wirednkod) [reply src/hooks/useBalance.ts:1]: I'll fix it here on this PR

File: src/hooks/useBalance.ts [hunk 12]
```diff
@@ -0,0 +1,89 @@
...
+import BN from 'bn.js';
+import { useEffect, useState } from 'react';
+
+import { useSourceTarget } from '../contexts/SourceTargetContextProvider';
+
+type State = [string, Balance, boolean, string];
+
+const ZERO = new BN(0);
+
+const useBalance = (address: string, providedSi: boolean = false): State[] => {
```
[the remark this answers is not in the document]
Comment (tomusdrw) [reply src/hooks/useBalance.ts]: > In this case the logic to show the balances is the following:

I'm pretty sure this is incorrect. The entire codebase should not care what kind of account is selected. There is always only:
- `source` chain - the one we are going to send the transaction to
- `target` chain - the one that will have a message delivered and will perform dispatch.

When user selects an account in the dropdown, the correct `source/target` variables should be set accordingly, so when user selects Rialto:Alice, the `source` chain should be pointing to `Rialto`. When the user selects `Millau:Alice` the `source` chain should be pointing to `Millau`. Selecting accounts from different networks should cause the UI to switch `source/target` pair correctly.

File: src/components/Accounts.tsx [hunk 13]
```diff
@@ -53,8 +53,8 @@ const Accounts = ({ className }: Props) => {
   const onChange = (value: string, chain: string) => {
     setCurrentAccount(value, chain);
   };
-
   const renderAccounts = (chain: string) => {
+    console.log('chain is:', chain);
```
Comment (tomusdrw) [inline src/components/Accounts.tsx:57]: stray log

File: src/hooks/useBalance.ts (hunk 12 above)
[the remark this answers is not in the document]
Comment (tomusdrw) [reply src/hooks/useBalance.ts]: I think I've jumped to conclusion too early. So the code seems correct now and the logic described here seems correct too. I think the complication comes from the way we use hooks and how we treat accounts.

I wonder if we could always associate accounts with their chains. I.e. every time you receive `account` it's not only just account id, but it actually always have an `api` or at least `chainName` associated with it, so that if you use any util functions there is no confusion what api / chain to use.

[the remark this answers is not in the document]
Comment (hbulgarini) [reply src/hooks/useBalance.ts]: The logic i described is correct i think , because the purpose of this is to show as well the balances within the account select component. If you check the designs you will see that you have the accounts from both chains with their respective derived account balance. 
For the sake of consistency and how the code was built, when initially the select is open there is already a source and target defined.

File: src/components/Accounts.tsx (hunk 13 above)
Comment (wirednkod) [reply src/components/Accounts.tsx:57]: Its not stray - Its called Jack and its my console log - I pet it and feed it 😄

File: src/hooks/useBalance.ts [hunk 14]
```diff
@@ -0,0 +1,107 @@
...
+        return Promise.resolve(u);
+      } catch (e) {
+        dispatchMessage(MessageActionsCreators.triggerErrorMessage({ message: e.message }));
+        logger.error(e.message);
+        return Promise.reject();
+      }
+    };
+
+    if (address) {
+      console.log('name: ', name, 'address', address, ' => derievedAddress', derivedAddress);
```
Comment (hbulgarini) [inline src/hooks/useBalance.ts:94]: If this is something you want to log, please use the `logger` helper

**Review by hbulgarini — APPROVED** [review]
LGTM !  There is one small comment to address but you can merge as soon as it is addressed.

**Review by hbulgarini — APPROVED** [review]
LGTM ! There is one small comment to address but you can merge as soon as it is addressed.
