### PR TITLE
Fix how UI reacts when APIs are not connected

### LINKED ISSUE #15: Avoid page breaking when the API is not connected.

### PR DESCRIPTION
**Pull request by wirednkod**
Fixes #15 

Besides avoiding the breaking of UI when API is disconnected, enhancement has been added concerning the fact that 1 of the 2 APIs is not connected and not only both. 
Relevant Icons were added next to chain names at the sidebar.

connected
disconnected
source only disconnected
Screenshot from 2021-05-18 14-09-00

### CODE REVIEW

File: src/components/ExtensionAccountCheck.tsx [hunk 1]
```diff
@@ -16,22 +16,33 @@
...
   component: JSX.Element;
 }
 
+// TODO: Move this to a more generic error-show component
+const statusFunc = (from: string, state: boolean) => `${from} chain status: ${!state ? 'disconnected' : 'connected'}`;
+
 const ExtensionAccountCheck = ({ component }: Props): JSX.Element => {
   const { extensionExists, accountExists } = useKeyringContext();
+  // TODO: Move this to a more generic error-show component
+  const { sourceReady, targetReady } = useLoadingApi();
```
Comment (hbulgarini) [inline src/components/ExtensionAccountCheck.tsx:31]: This values are already available on `useSourceTarget`, but i'm fine if you want to retrieve them from the `useLoadingApi` for readability

File: src/hooks/useApiConnection.ts [hunk 2]
```diff
@@ -78,7 +78,7 @@ export function useApiConnection(connectionDetails: ConnectionChainInformation):
       setConfigs(values);
     };
 
-    if (isReady && isEmpty(configs)) {
+    if (apiPromise.isReady && isEmpty(configs)) {
       getChainConfigs();
     }
   }, [apiPromise, configs, isReady]);
```
Comment (hbulgarini) [inline src/hooks/useApiConnection.ts:84]: do we need `isReady` dependency?

File: src/hooks/useLoadingApi.ts [hunk 3]
```diff
@@ -29,10 +35,18 @@ export default function useLoadingApi(): boolean {
   } = useSourceTarget();
 
   const [areReady, setAreReady] = useState(false);
+  const [isSourceReady, setIsSourceReady] = useState(false);
```
Comment (hbulgarini) [inline src/hooks/useLoadingApi.ts:38]: Can you please elaborate why are we replicating the value coming from `useSourceTarget` to this local state?

**Review by hbulgarini — CHANGES_REQUESTED** [review]

File: src/components/Network.tsx [hunk 4]
```diff
@@ -58,11 +65,13 @@ export const NetworkSides = () => {
   const { sourceChainDetails, targetChainDetails } = useSourceTarget();
   const dbSource = useDashboard(ChainDetails.SOURCE);
   const dbTarget = useDashboard(ChainDetails.TARGET);
+  const { sourceReady, targetReady } = useLoadingApi();
```
[the remark this answers is not in the document]
Comment (wirednkod) [reply src/components/Network.tsx:68]: Yes and no. I prefer to have a useLoadingApi() (as soon as it already existed) - that I will be able to know at once the state of both chains and of each one of them. I just extended the functionality. Also useSourceTarget is not used everywhere where the useLoading is needed.

File: src/components/ExtensionAccountCheck.tsx (hunk 1 above)
Comment (wirednkod) [reply src/components/ExtensionAccountCheck.tsx:31]: Its not only a matter of readability but also of simplicity.
useSourceTarget carries much more than needed while useLoadingApi hook is straightforward.
For the first you need minimum to do:
```
const {
    sourceChainDetails: {
      sourceApiConnection: { isApiReady: sourceIsApiReady }
    },
    targetChainDetails: {
      targetApiConnection: {  isApiReady: targetIsApiReady }
    }
  } = useSourceTarget();
  ```
  while for the latter its less code and simpler.

File: src/hooks/useApiConnection.ts (hunk 2 above)
Comment (wirednkod) [reply src/hooks/useApiConnection.ts:84]: Yes you do. If `apiPromise.isReady` is removed then on `getConfigs` you will receive on:
```
const systemChain = await apiPromise.rpc.system.name();
```
a `rpc of undefined not found` or something like that (happened to me)

File: src/hooks/useLoadingApi.ts (hunk 3 above)
Comment (wirednkod) [reply src/hooks/useLoadingApi.ts:38]: Makes importing and re-usability easy. Imagine you have a file that both areReady and each one API state state is needed.
You will have to import both `useLoading` and `useSourceTarget` hooks in order to get all Values.
As soon as useLoading hook exist and is used in order to ensure that API are ready for usage - then it made much more sense to extend it and reuse it than import yet another hook to retrieve info that I could get from the same hook

File: src/App.tsx [hunk 5]
```diff
@@ -27,13 +27,14 @@ import { SourceTargetContextProvider } from './contexts/SourceTargetContextProvi
...
+import { isEmpty } from 'lodash';
 
 const [connectionDetails1, connectionDetails2] = substrateProviders();
 
 function App() {
-  const { connections, apiReady } = useConnections([connectionDetails1, connectionDetails2]);
+  const { connections } = useConnections([connectionDetails1, connectionDetails2]);
 
-  if (!apiReady) {
+  if (isEmpty(connections)) {
```
Comment (tomusdrw) [inline src/App.tsx:37]: Under what circumstances can this happen?

File: src/App.tsx [hunk 6]
```diff
@@ -27,13 +27,14 @@ import { SourceTargetContextProvider } from './contexts/SourceTargetContextProvi
 import { TransactionContextProvider } from './contexts/TransactionContext';
 import { useConnections } from './hooks/useConnections';
 import Main from './screens/Main';
+import { isEmpty } from 'lodash';
```
Comment (tomusdrw) [inline src/App.tsx:30]: Is it really needed? Like isn't it just doing `parameter.length === 0`?

File: src/components/ExtensionAccountCheck.tsx [hunk 7]
```diff
@@ -16,22 +16,33 @@
...
     msg = 'There are no accounts in the extension. Please create one';
+    // TODO: Move this to a more generic error-show component
+  } else if (!sourceReady || !targetReady) {
+    msg = `${!sourceReady ? statusFunc('Source', sourceReady) : ''} ${
+      !targetReady ? statusFunc('Target', targetReady) : ''
+    }`;
   }
 
-  return <>{accountExists ? component : <Alert severity="error">{msg}</Alert>}</>;
+  return <>{accountExists && sourceReady && targetReady ? component : <Alert severity="error">{msg}</Alert>}</>;
```
Comment (tomusdrw) [inline src/components/ExtensionAccountCheck.tsx:45]:
```suggestion
  return <>{msg ? <Alert severity="error">{msg}</Alert> : component}</>;
```

File: src/components/Transactions.tsx [hunk 8]
```diff
@@ -37,7 +37,7 @@ const Transactions = ({ type, ...transactionDisplayProps }: Props) => {
 
   return (
     <>
-      {transactions.length ? (
+      {transactions?.length ? (
```
Comment (tomusdrw) [inline src/components/Transactions.tsx:40]: Can it be `null/undefined` now? Why it wasn't before this PR?

File: src/hooks/useApiConnection.ts (hunk 2 above)
Comment (tomusdrw) [reply src/hooks/useApiConnection.ts:84]: We probably need `[apiPromise, apiPromise.isReady, configs]` instead.

File: src/hooks/useLoadingApi.ts (hunk 3 above)
Comment (tomusdrw) [reply src/hooks/useLoadingApi.ts:38]: The 2 extra `useState`s for that are not necessary, we can simply return `isSourceApiReady` and `isTargetApiReady` (we do need the state variable for `areReady` though).

File: src/App.tsx (hunk 5 above)
Comment (wirednkod) [reply src/App.tsx:37]: When chain1Configs or chain2Configs is empty -> meaning for each chain - when the API is not connected:
https://github.com/paritytech/parity-bridges-ui/blob/5e8851725cb774981b88ef3c4fea8732978ffede/src/hooks/useApiConnection.ts#L81
If this does not happen, then getChainConfigs will not run, and thus configs will be empty...

File: src/App.tsx (hunk 6 above)
Comment (wirednkod) [reply src/App.tsx:30]: It is needed as connections is a Json object and that would not work.
What I could do is `Object.keys(parameter).length === 0`. That would work - should I change it?

File: src/components/ExtensionAccountCheck.tsx (hunk 7 above)
Comment (wirednkod) [reply src/components/ExtensionAccountCheck.tsx:45]: ............. you got me there

File: src/components/Transactions.tsx (hunk 8 above)
Comment (wirednkod) [reply src/components/Transactions.tsx:40]: It collapsed when I removed the API connections for test reasons. It probably remained - I'll remove it (even though I think that there is no harm for it to be there)

**Comment by wirednkod** [comment]
https://github.com/paritytech/parity-bridges-ui/pull/173#discussion_r634521338

As soon as isReady is a boolean (primitive - and we are using Typescript - meaning that it probably wont change) then this is not actually needed. Even though "it is said" that as a primitive dependency, it should work just fine - that is not a guarantee and it is better always to add the dependencies - so I'll add this one.

File: src/hooks/useLoadingApi.ts (hunk 3 above)
Comment (wirednkod) [reply src/hooks/useLoadingApi.ts:38]: I prefer to know the init state upon first call of the hook (false) instead of initializing the states from another state that is not known at the moment. The performance is the same as the 1st useEffect will run anyway and more control is provided.
If we do not want that then no state is needed for any of the cases. We can just: 
```
return {
    areApiReady: isSourceApiReady && isTargetApiReady,
    sourceReady: isSourceApiReady,
    targetReady: isTargetApiReady
  };
  ```
  but I do not like it as it is too float-y

**Comment by wirednkod** [comment]
@tomusdrw concerning https://github.com/paritytech/parity-bridges-ui/pull/173#discussion_r634523303

I do not agree. The primitive hooks (useState, useEffect etc) should be used inside a custom hook in order to verify that the rerender of components using them is happening efficiently.

File: src/hooks/useLoadingApi.ts (hunk 3 above)
Comment (hbulgarini) [reply src/hooks/useLoadingApi.ts:38]: > The 2 extra `useState`s for that are not necessary, we can simply return `isSourceApiReady` and `isTargetApiReady` (we do need the state variable for `areReady` though).

This is my exactly my point.

File: src/App.tsx (hunk 6 above)
Comment (tomusdrw) [reply src/App.tsx]: Ah I see. Fair enough, let's keep `isEmpty`.

File: src/components/Transactions.tsx (hunk 8 above)
Comment (tomusdrw) [reply src/components/Transactions.tsx]: I'd rather make sure we use correct typings so that this kind of stuff is not necessary. I'm not against it, just the change seemed a bit random.

File: src/hooks/useApiConnection.ts (hunk 2 above)
Comment (tomusdrw) [reply src/hooks/useApiConnection.ts]: @wirednkod `isReady` is not used within the `useEffect`, so I feel there is something weird happening here. Like obviously it works, it just indicates something fishy. Why do we check `apiPromise.isReady` and not `isReady`? Shouldn't the two be synchronized anyway?

File: src/App.tsx (hunk 6 above)
Comment (wirednkod) [reply src/App.tsx]: I prefer to avoid 3rd party libraries where I can (and here I can :) )

File: src/hooks/useLoadingApi.ts (hunk 3 above)
Comment (tomusdrw) [reply src/hooks/useLoadingApi.ts:38]: > but I do not like it as it is too float-y. 

Can you elaborate what problem exactly this creates? I'm abstracting from all the bloat that comes from (`useSourceTarget -> Context -> `connections` passed as props -> `useConnections` hook), but essentially we already have a "state" that we maintain in the top level component that knows if api is ready or not. The hook that you propose is creating local copies of these variables, so now instead of having one "source of truth" we have two and you have to use `useEffect` to keep them in sync.
Obviously, we can argue that the thanks to this the state is more local and it's maybe easier to reason about the hook itself, but long term it's much harder to reason about the entire application - this is just covering bloated code with even more bloated code and we will easily loose track of what is happening where. These kind of things lead to subtle bugs (one component thinks "ready", while other is "not ready") and I feel that historically a solution to these kinds of bugs is just adding more bloat (we miss `useEffect` here, or a dependency in existing `useEffect`, etc).

File: src/hooks/useApiConnection.ts (hunk 2 above)
Comment (wirednkod) [reply src/hooks/useApiConnection.ts]: The `isReady` is expecting the `apiPromise.isReady` to be true and the `configs` to be empty in order to retrieve them.
On line `59` (https://github.com/paritytech/parity-bridges-ui/blob/5e8851725cb774981b88ef3c4fea8732978ffede/src/hooks/useApiConnection.ts#L59-L62) there is a similar check but where `isReady` is false. If here we checked the `isReady` we must wait for `apiPromise.isReady` + 1 render to make the `isReady` true, in order to finally get the `configs`. There is no reason to do that - saves us 1 extra render.

File: src/hooks/useLoadingApi.ts (hunk 3 above)
Comment (wirednkod) [reply src/hooks/useLoadingApi.ts:38]: Agreed and understood your point. I will remove the non-needed useState/useEffect from this component. 
At the end - this component is just a way to "receive" simpler and faster the states of API across the app.

**Review by hbulgarini — APPROVED** [review]
awesome! great work

**Comment by hbulgarini** [comment]
@wirednkod  please resolve the conflicts before merge.

File: src/components/Sender.tsx [hunk 9]
```diff
@@ -130,11 +133,14 @@ const Sender = () => {
     return <AccountDisplay friendlyName="Select sender account" hideAddress />;
   };
 
+  console.log('areApiReady', areApiReady);
```
Comment (hbulgarini) [inline src/components/Sender.tsx:136]: unwanted debug

**Review by hbulgarini — CHANGES_REQUESTED** [review]

File: src/components/ExtensionAccountCheck.tsx [hunk 10]
```diff
@@ -16,22 +16,33 @@
 import React from 'react';
 import { Alert } from '.';
 import { useKeyringContext } from '../contexts/KeyringContextProvider';
+import useLoadingApi from '../hooks/useLoadingApi';
 
 interface Props {
   component: JSX.Element;
 }
 
+// TODO: Move this to a more generic error-show component
```
[the remark this answers is not in the document]
Comment (tomusdrw) [reply src/components/ExtensionAccountCheck.tsx:25]: Please add issue number to `TODO`,

**Review by tomusdrw — APPROVED** [review]

**Review by hbulgarini — APPROVED** [review]
